time-format = "%T"
[formatting]
flatten = "never"

[formatting.punctuation]
logger-name-separator = ":"
field-key-value-separator = "="
string-opening-quote = "'"
string-closing-quote = "'"
source-location-separator = "→ "
caller-name-file-separator = " @ "
hidden-fields-indicator = " ..."
level-left-separator = "["
level-right-separator = "]"
input-number-left-separator = ""
input-number-prefix = "#"
input-number-right-separator = " │ "
input-name-left-separator = ""
input-name-right-separator = " │ "
input-name-clipping = "··"
input-name-common-part = "··"
array-separator = ", "
