#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d     
bspc monitor -d WEB CODE TERM ETC CHAT

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config single_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           0
bspc config normal_border_color   '#333333'
bspc config focused_border_color  '#444444'

bspc rule -a Discord desktop='^5'
bspc rule -a Teams desktop='^5'
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh
feh --bg-fill $HOME/.config/bspwm/background.png
xset r rate 200 60
dunst &
