#!/bin/zsh
yabai -m config layout bsp
yabai -m config window_topmost on

# yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0
yabai -m config window_topmost true

# rules
yabai -m rule --add app="^Emacs$" manage=on

# array of applications that will not get managed
UNMANAGED_APPS=(
    "JetBrains Toolbox"
    "^System Preferences$"
    "^Karabiner*"
)

for app in "${UNMANAGED_APPS[@]}"
do
    yabai -m rule --add app=$app manage=off
    echo $app
done
