#!/bin/zsh
yabai -m config layout bsp
# yabai -m config window_topmost on

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     12
yabai -m config window_zoom_persist off
# yabai -m config window_topmost on
yabai -m config auto_balance   on

# rules
yabai -m rule --add app="^Emacs$" manage=on

# array of applications that will not get managed
UNMANAGED_APPS=(
    "JetBrains Toolbox"
    "Python"
    "python"
    "^System Settings$"
    "^Karabiner*"
    "zig-raylib"
    "odin-test"
    "soa"
    "SDL2"
    "sdl2"
    "^Oklch Color Picker$"
    # "^Quartz*"
    # "^Xcode$"
)

for app in "${UNMANAGED_APPS[@]}"
do
    yabai -m rule --add app=$app manage=off
done
