(menu-bar-mode -1)

(setq frame-resize-pixelwise t)
(setq frame-inhibit-implied-resize t)

(setq-default tab-width 4)
(setq create-lockfiles nil)
(setq make-backup-files nil)
(setq delete-by-moving-to-trash t)
(setq ring-bell-function 'ignore)
(setq auto-save-default nil)
(setq use-dialog-box nil)
(setq inhibit-startup-message t)
(setq use-short-answers t)
(setq mouse-wheel-scroll-amount '(5))
(setq mouse-wheel-progressive-speed nil)
(setq scroll-conservatively 0)
(setq scroll-step 1)
(setq scroll-margin 0)
(setq maximum-scroll-margin 0)
(setq scroll-preserve-screen-position t)
(setq use-file-dialog nil)
(setq use-dialog-box nil)

(defmacro load-module (module)
  `(load-file (expand-file-name ,(format "modules/%s.el" (symbol-name module)) user-emacs-directory)))

(load-module ui)
(load-module editor)
(load-module files)
(load-module llm)
(load-module org)
(load-module terminal)
(load-module languages)
