(defmacro load-module (module)
  `(load-file (expand-file-name ,(format "modules/%s.el" (symbol-name module)) user-emacs-directory)))

;;; init elpaca
(load-file (expand-file-name "init-elpaca.el" user-emacs-directory))

(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(if (file-exists-p custom-file)
    (load custom-file))

(dolist (variable '(initial-frame-alist default-frame-alist))
  (set variable `((horizontal-scroll-bars . nil)
                  (vertical-scroll-bars . nil)
                  (menu-bar-lines . 0)
                  (tool-bar-lines . 0))))

(use-package exec-path-from-shell :ensure t)
(setq-default tab-width 8)
(setq-default indent-tabs-mode nil)
(setq frame-resize-pixelwise t)
(setq frame-inhibit-implied-resize t)
(setq create-lockfiles nil)
(setq make-backup-files nil)
(setq delete-by-moving-to-trash t)
(setq ring-bell-function 'ignore)
(setq auto-save-default nil)
(setq use-dialog-box nil)
(setq inhibit-startup-message t)
(setq use-short-answers t)
(setq mouse-wheel-scroll-amount '(8))
(setq mouse-wheel-progressive-speed nil)
;; (setq scroll-conservatively 101)
;; (setq scroll-step 1)
;; (setq scroll-margin 0)
;; (setq maximum-scroll-margin 0)
(setq scroll-preserve-screen-position t)
(setq use-file-dialog nil)
(setq use-dialog-box nil)

(load-module ui)
(load-module terminal)
(load-module editor)
(load-module files)
(load-module llm)
(load-module org)
(load-module languages)
